// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXtBpNKNV-r-TGEtyN-Qe-gCr_ItgZFoc',
    appId: '1:1075574521581:web:2e85f888f63bc3dcc416e4',
    messagingSenderId: '1075574521581',
    projectId: 'gestor-proyectos-app-7c229',
    authDomain: 'gestor-proyectos-app-7c229.firebaseapp.com',
    storageBucket: 'gestor-proyectos-app-7c229.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHtPwXoDjD3RpYB0e-UrBN5grQOZIFkYU',
    appId: '1:1075574521581:android:d4d16b3b5b2ae3adc416e4',
    messagingSenderId: '1075574521581',
    projectId: 'gestor-proyectos-app-7c229',
    storageBucket: 'gestor-proyectos-app-7c229.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSjwVk5xcSW8S7V7nPlpFHSCCI_jVSm1E',
    appId: '1:1075574521581:ios:b94d44a80fba1665c416e4',
    messagingSenderId: '1075574521581',
    projectId: 'gestor-proyectos-app-7c229',
    storageBucket: 'gestor-proyectos-app-7c229.firebasestorage.app',
    iosBundleId: 'com.example.gestorProyectosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSjwVk5xcSW8S7V7nPlpFHSCCI_jVSm1E',
    appId: '1:1075574521581:ios:b94d44a80fba1665c416e4',
    messagingSenderId: '1075574521581',
    projectId: 'gestor-proyectos-app-7c229',
    storageBucket: 'gestor-proyectos-app-7c229.firebasestorage.app',
    iosBundleId: 'com.example.gestorProyectosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXtBpNKNV-r-TGEtyN-Qe-gCr_ItgZFoc',
    appId: '1:1075574521581:web:fa455f96b791bfedc416e4',
    messagingSenderId: '1075574521581',
    projectId: 'gestor-proyectos-app-7c229',
    authDomain: 'gestor-proyectos-app-7c229.firebaseapp.com',
    storageBucket: 'gestor-proyectos-app-7c229.firebasestorage.app',
  );
}
